name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
    - name: Repository klónozása
      uses: actions/checkout@v2

    - name: Node.js verzió beállítása
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Függőségek telepítése
      run: npm install

    - name: Tesztek futtatása
      run: npm test